Change config/service references in JS/Livewire components to updated laravelgoogleapi package #72 #75 [TGER-133,140]
tipoff/addresses pull request #148
Opened 2021-04-27 15:22 UTC by devjk1

#72 #75 

- (JS component) change config reference to updated laravel-google-api package
- (Livewire) change service reference to updated laravel-google-api package

2021-04-30 07:35 UTC, joshtorres commented
@phuclh can you take a look at this one.

2021-05-01 07:13 UTC, joshtorres requested changes
@phuclh please review since you worked on these components as well

2021-05-01 16:14 UTC, phuclh approved these changes
Looks good 👯‍♂️

2021-05-01 18:52 UTC, joshtorres approved these changes

2021-05-01 18:52 UTC, merged